export const dataList=[
    {name:'云智能基础产品事业部-安全-商业化产品经理-杭州afjkjjfksajfakslfjkasdfjkadjfjkf',area:'杭州',time:'3分钟前',
      url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-技术市场专家',area:'上海',time:'3分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'盒马-金牌店长招募令-北京',area:'北京',time:'3分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'搜索事业部-高级前端开发工程师-杭州',area:'杭州',time:'14分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-SoC验证专家 -上海',area:'上海',time:'25分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'数据计算-计算技术-Neuromorphic Architecture Research Scientist',area:'上海',time:'1小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'阿里集团-CTO线-安全生产产品专家-杭州',area:'杭州',time:'1小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-Staff Engineer, DFT-Sunnyvale, US',area:'北京',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'阿里妈妈事业部-品牌广告产品专家-北京',area:'北京',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-SoC验证专家',area:'北京',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'搜索事业部-高级前端开发工程师-杭州',area:'杭州',time:'4小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'云智能基础产品事业部-安全-商业化产品经理-杭州',area:'杭州',time:'3分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-技术市场专家',area:'上海',time:'3分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'盒马-金牌店长招募令-北京',area:'北京',time:'3分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'搜索事业部-高级前端开发工程师-杭州',area:'杭州',time:'14分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-SoC验证专家 -上海',area:'上海',time:'25分钟前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'数据计算-计算技术-Neuromorphic Architecture Research Scientist',area:'上海',time:'1小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'阿里集团-CTO线-安全生产产品专家-杭州',area:'杭州',time:'1小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-Staff Engineer, DFT-Sunnyvale, US',area:'北京',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'阿里妈妈事业部-品牌广告产品专家-北京',area:'北京',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'平头哥-IoT芯片-SoC验证专家',area:'',time:'2小时前',url:'https://job.alibaba.com/zhaopin/index.htm'},
    {name:'搜索事业部-高级前端开发工程师-杭州',area:'杭州',time:'4小时前',url:'https://job.alibaba.com/zhaopin/index.htm'}
  ]